### ISSUE TITLE
not indexing certain property objects

### ISSUE THREAD

**Issue by eroux** [buda-base/jena-issues#4]
Jena already has a way to assign some configuration to the objects of certain properties ([ex](https://github.com/BuddhistDigitalResourceCenter/buda-base/blob/master/conf/fuseki/ttl.erb#L387)), maybe there could be a way to say "don't index the objects of this property in Lucene at all", we could use that for:
- `adm:logMessage`
- `bdo:placeRegionPoly`

and probably a few others

**Comment by xristy** [comment]
Maybe I'm misunderstanding, but only properties listed in the ttl.erb ``text:map`` are [indexed by Lucene](https://github.com/BuddhistDigitalResourceCenter/jena/blob/1f5edddde6dc8a9a1beed5a96262adcf39bbc0f4/jena-text/src/main/java/org/apache/jena/query/text/TextQueryFuncs.java#L73).

The ``adm:logMessage`` can be removed from the ``text:map`` but I don't see it as adding much to the index. The messages aren't ``rdf:langString`` so don't have any extra fields added to their docs and eventually I would hope that log messages could have useful content for doing foresics

**Comment by eroux** [comment]
Oh ok ! I misunderstood, sorry!
